///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Scenario2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("bbbd4f98-cebe-4371-aaf3-7f44a561ac64", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Scenario2Repository repository.
        /// </summary>
        public static Scenario2Repository repo = Scenario2Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap' at 16;6.", repo.ApplicationUnderTest.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.GirişYap.Click("16;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.UEyeOl1' at 19;9.", repo.ApplicationUnderTest.LoginRegister.UEyeOl1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.LoginRegister.UEyeOl1.Click("19;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.UEyeOl' at 21;7.", repo.ApplicationUnderTest.LoginRegister.UEyeOlInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.LoginRegister.UEyeOl.Click("21;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.EPostaVeŞifreniziGiriniz'.", repo.ApplicationUnderTest.EPostaVeŞifreniziGirinizInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ApplicationUnderTest.EPostaVeŞifreniziGirinizInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 32;18.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RegisterEmail.Click("32;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'zafercakar77{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmail.com' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("zafercakar77{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.TyCheck' at 6;4.", repo.ApplicationUnderTest.LoginRegister.TyCheckInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.LoginRegister.TyCheck.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.UEyeOl' at 22;8.", repo.ApplicationUnderTest.LoginRegister.UEyeOlInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.LoginRegister.UEyeOl.Click("22;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.BuEPostaAdresiKullanılamazLuetfen'.", repo.ApplicationUnderTest.BuEPostaAdresiKullanılamazLuetfenInfo, new RecordItemIndex(8));
            Validate.Exists(repo.ApplicationUnderTest.BuEPostaAdresiKullanılamazLuetfenInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 182;21.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.RegisterEmail.Click("182;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 25}' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("{Back 25}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPasswordInput' at 71;26.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.RegisterPasswordInput.Click("71;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '460219Az' with focus on 'ApplicationUnderTest.RegisterPasswordInput'.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.RegisterPasswordInput.PressKeys("460219Az");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.Fill1' at 3;5.", repo.ApplicationUnderTest.LoginRegister.Fill1Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.LoginRegister.Fill1.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.QButtonQButtonMediumQFluidQPrima' at 92;30.", repo.ApplicationUnderTest.LoginRegister.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.LoginRegister.QButtonQButtonMediumQFluidQPrima.Click("92;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.EPostaVeŞifreniziGiriniz'.", repo.ApplicationUnderTest.EPostaVeŞifreniziGirinizInfo, new RecordItemIndex(15));
            Validate.Exists(repo.ApplicationUnderTest.EPostaVeŞifreniziGirinizInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
