///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Scenario2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Scenario2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8a1935ac-6b20-438d-a505-51821ccbb84c")]
    public partial class Scenario2Repository : RepoGenBaseFolder
    {
        static Scenario2Repository instance = new Scenario2Repository();
        Scenario2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Scenario2Repository element repository.
        /// </summary>
        [RepositoryFolder("8a1935ac-6b20-438d-a505-51821ccbb84c")]
        public static Scenario2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Scenario2Repository() 
            : base("Scenario2Repository", "/", null, 0, false, "8a1935ac-6b20-438d-a505-51821ccbb84c", ".\\RepositoryImages\\Scenario2Repository8a1935ac.rximgres")
        {
            _applicationundertest = new Scenario2RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8a1935ac-6b20-438d-a505-51821ccbb84c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a7b0b728-1303-4525-a159-c5a08ffbb2ef")]
        public virtual Scenario2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Scenario2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a7b0b728-1303-4525-a159-c5a08ffbb2ef")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Scenario2RepositoryFolders.LoginRegisterFolder _loginregister;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _epostaveşifrenizigirinizInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _buepostaadresikullanılamazluetfenInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "a7b0b728-1303-4525-a159-c5a08ffbb2ef", "")
            {
                _loginregister = new Scenario2RepositoryFolders.LoginRegisterFolder(this);
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "7c5a8dd8-f0c0-467b-a5c1-5ae813a5d1b3");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "d071700d-f8ed-42ff-a0cf-ee47f5f25ee0");
                _epostaveşifrenizigirinizInfo = new RepoItemInfo(this, "EPostaVeŞifreniziGiriniz", ".//div[#'error-box-wrapper']/span[@innertext>'E-posta ve şifrenizi giri']", ".//div[#'error-box-wrapper']/span[@innertext>'E-posta ve şifrenizi giri']", 30000, null, "8caf4e89-331b-40f1-b1af-f852de4df8a6");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "0f474c43-7e17-4e36-ae7f-2293d865240a");
                _buepostaadresikullanılamazluetfenInfo = new RepoItemInfo(this, "BuEPostaAdresiKullanılamazLuetfen", ".//div[#'error-box-wrapper']/span[@innertext>'Bu e-posta adresi kullanılamaz.']", ".//div[#'error-box-wrapper']/span[@innertext>'Bu e-posta adresi kullanılamaz.']", 30000, null, "a2220155-21ff-4f0a-86d2-af23116702e9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7b0b728-1303-4525-a159-c5a08ffbb2ef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7b0b728-1303-4525-a159-c5a08ffbb2ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("7c5a8dd8-f0c0-467b-a5c1-5ae813a5d1b3")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("7c5a8dd8-f0c0-467b-a5c1-5ae813a5d1b3")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("d071700d-f8ed-42ff-a0cf-ee47f5f25ee0")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("d071700d-f8ed-42ff-a0cf-ee47f5f25ee0")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The EPostaVeŞifreniziGiriniz item.
            /// </summary>
            [RepositoryItem("8caf4e89-331b-40f1-b1af-f852de4df8a6")]
            public virtual Ranorex.SpanTag EPostaVeŞifreniziGiriniz
            {
                get
                {
                    return _epostaveşifrenizigirinizInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EPostaVeŞifreniziGiriniz item info.
            /// </summary>
            [RepositoryItemInfo("8caf4e89-331b-40f1-b1af-f852de4df8a6")]
            public virtual RepoItemInfo EPostaVeŞifreniziGirinizInfo
            {
                get
                {
                    return _epostaveşifrenizigirinizInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("0f474c43-7e17-4e36-ae7f-2293d865240a")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("0f474c43-7e17-4e36-ae7f-2293d865240a")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The BuEPostaAdresiKullanılamazLuetfen item.
            /// </summary>
            [RepositoryItem("a2220155-21ff-4f0a-86d2-af23116702e9")]
            public virtual Ranorex.SpanTag BuEPostaAdresiKullanılamazLuetfen
            {
                get
                {
                    return _buepostaadresikullanılamazluetfenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BuEPostaAdresiKullanılamazLuetfen item info.
            /// </summary>
            [RepositoryItemInfo("a2220155-21ff-4f0a-86d2-af23116702e9")]
            public virtual RepoItemInfo BuEPostaAdresiKullanılamazLuetfenInfo
            {
                get
                {
                    return _buepostaadresikullanılamazluetfenInfo;
                }
            }

            /// <summary>
            /// The LoginRegister folder.
            /// </summary>
            [RepositoryFolder("c0904db8-2ce7-4d25-92d0-316b6eaec02a")]
            public virtual Scenario2RepositoryFolders.LoginRegisterFolder LoginRegister
            {
                get { return _loginregister; }
            }
        }

        /// <summary>
        /// The LoginRegisterFolder folder.
        /// </summary>
        [RepositoryFolder("c0904db8-2ce7-4d25-92d0-316b6eaec02a")]
        public partial class LoginRegisterFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cinsiyetopsiyonelInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _tycheckInfo;
            RepoItemInfo _ueyeol1Info;
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _fill1Info;

            /// <summary>
            /// Creates a new LoginRegister  folder.
            /// </summary>
            public LoginRegisterFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginRegister", ".//div[#'login-register']", parentFolder, 30000, null, false, "c0904db8-2ce7-4d25-92d0-316b6eaec02a", "")
            {
                _cinsiyetopsiyonelInfo = new RepoItemInfo(this, "CinsiyetOpsiyonel", ".//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/label[@innertext='Cinsiyet (Opsiyonel)']", ".//label[@innertext='Cinsiyet (Opsiyonel)']", 30000, null, "27524836-4632-4acd-8a49-1eaa816c1969");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/span[@innertext='Üye Ol']", ".//form/button/span[@innertext='Üye Ol']", 30000, null, "1c5cc015-de11-4a64-a760-f33ee7ac3044");
                _tycheckInfo = new RepoItemInfo(this, "TyCheck", "div[3]/?/?/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[6]//svg", ".//form/div[6]/div/div[1]/div/svg", 30000, null, "8a00c502-833b-4475-bb42-99d76cdd314a");
                _ueyeol1Info = new RepoItemInfo(this, "UEyeOl1", "div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//span[@innertext='Üye Ol']", 30000, null, "61be7d93-e04e-4a5d-aea7-c586696400c1");
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", ".//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//form/button", 30000, null, "a4a86c8e-ed83-4873-a7a0-404cc3db45cb");
                _fill1Info = new RepoItemInfo(this, "Fill1", "div[3]/div[1]/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[6]/div/div[1]//use[@id='Fill-1']", ".//form/div[6]/div/div[1]/div/svg/g/g/g/g/use[@id='Fill-1']", 30000, null, "593ff849-dc52-4c9e-a714-f4f0e88f84b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0904db8-2ce7-4d25-92d0-316b6eaec02a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0904db8-2ce7-4d25-92d0-316b6eaec02a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CinsiyetOpsiyonel item.
            /// </summary>
            [RepositoryItem("27524836-4632-4acd-8a49-1eaa816c1969")]
            public virtual Ranorex.LabelTag CinsiyetOpsiyonel
            {
                get
                {
                    return _cinsiyetopsiyonelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The CinsiyetOpsiyonel item info.
            /// </summary>
            [RepositoryItemInfo("27524836-4632-4acd-8a49-1eaa816c1969")]
            public virtual RepoItemInfo CinsiyetOpsiyonelInfo
            {
                get
                {
                    return _cinsiyetopsiyonelInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("1c5cc015-de11-4a64-a760-f33ee7ac3044")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("1c5cc015-de11-4a64-a760-f33ee7ac3044")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The TyCheck item.
            /// </summary>
            [RepositoryItem("8a00c502-833b-4475-bb42-99d76cdd314a")]
            public virtual Ranorex.SvgTag TyCheck
            {
                get
                {
                    return _tycheckInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The TyCheck item info.
            /// </summary>
            [RepositoryItemInfo("8a00c502-833b-4475-bb42-99d76cdd314a")]
            public virtual RepoItemInfo TyCheckInfo
            {
                get
                {
                    return _tycheckInfo;
                }
            }

            /// <summary>
            /// The UEyeOl1 item.
            /// </summary>
            [RepositoryItem("61be7d93-e04e-4a5d-aea7-c586696400c1")]
            public virtual Ranorex.SpanTag UEyeOl1
            {
                get
                {
                    return _ueyeol1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl1 item info.
            /// </summary>
            [RepositoryItemInfo("61be7d93-e04e-4a5d-aea7-c586696400c1")]
            public virtual RepoItemInfo UEyeOl1Info
            {
                get
                {
                    return _ueyeol1Info;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("a4a86c8e-ed83-4873-a7a0-404cc3db45cb")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("a4a86c8e-ed83-4873-a7a0-404cc3db45cb")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The Fill1 item.
            /// </summary>
            [RepositoryItem("593ff849-dc52-4c9e-a714-f4f0e88f84b2")]
            public virtual Ranorex.UseTag Fill1
            {
                get
                {
                    return _fill1Info.CreateAdapter<Ranorex.UseTag>(true);
                }
            }

            /// <summary>
            /// The Fill1 item info.
            /// </summary>
            [RepositoryItemInfo("593ff849-dc52-4c9e-a714-f4f0e88f84b2")]
            public virtual RepoItemInfo Fill1Info
            {
                get
                {
                    return _fill1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
