///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Scenario1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("8985ecde-2477-4e65-9b48-23734d6d3a3d", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Scenario1Repository repository.
        /// </summary>
        public static Scenario1Repository repo = Scenario1Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GirişYap' at 33;4.", repo.ApplicationUnderTest.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.GirişYap.Click("33;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UEyeOl' at 15;8.", repo.ApplicationUnderTest.UEyeOlInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UEyeOl.Click("15;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='') on item 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RegisterEmailInfo, "Value", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='') on item 'ApplicationUnderTest.RegisterPasswordInput'.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RegisterPasswordInputInfo, "Value", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.Kadın'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.KadınInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.KadınInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.Erkek'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.ErkekInfo, new RecordItemIndex(5));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.ErkekInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.SomeUseTag'.", repo.ApplicationUnderTest.SomeUseTagInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ApplicationUnderTest.SomeUseTagInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl1'.", repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl1Info, new RecordItemIndex(7));
            Validate.Exists(repo.ApplicationUnderTest.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
