///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Scenario1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Scenario1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ba45a8ce-d818-43dc-aab5-c8adbf019845")]
    public partial class Scenario1Repository : RepoGenBaseFolder
    {
        static Scenario1Repository instance = new Scenario1Repository();
        Scenario1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Scenario1Repository element repository.
        /// </summary>
        [RepositoryFolder("ba45a8ce-d818-43dc-aab5-c8adbf019845")]
        public static Scenario1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Scenario1Repository() 
            : base("Scenario1Repository", "/", null, 0, false, "ba45a8ce-d818-43dc-aab5-c8adbf019845", ".\\RepositoryImages\\Scenario1Repositoryba45a8ce.rximgres")
        {
            _applicationundertest = new Scenario1RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ba45a8ce-d818-43dc-aab5-c8adbf019845")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("790cd9cf-225e-4224-9f90-c3d84dcb5bfa")]
        public virtual Scenario1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Scenario1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("790cd9cf-225e-4224-9f90-c3d84dcb5bfa")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Scenario1RepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder _httpswwwtrendyolcomuyelikcbeqhttps;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _someusetagInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "790cd9cf-225e-4224-9f90-c3d84dcb5bfa", "")
            {
                _httpswwwtrendyolcomuyelikcbeqhttps = new Scenario1RepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder(this);
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "b1305b2e-0d45-45c3-9576-887cf9d859e5");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//div[#'login-register']/div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//div[#'login-register']//span[@innertext='Üye Ol']", 30000, null, "b5821da0-308f-4f54-9a70-80eaec8a3ae3");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "486adbe3-853d-4198-9161-63c5398686dd");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "6d8ff162-dba6-4f2c-a020-083d68e1cd0d");
                _someusetagInfo = new RepoItemInfo(this, "SomeUseTag", ".//div[#'login-register']/div[3]/div[1]/form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/div[6]/div/div[1]//use[@id='Fill-1']", ".//div[#'login-register']//form/div[6]/div/div[1]/div/svg/g/g/g/g/use[@id='Fill-1']", 30000, null, "af32cb56-1f18-4df1-b90b-32e12f2ad7a6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("790cd9cf-225e-4224-9f90-c3d84dcb5bfa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("790cd9cf-225e-4224-9f90-c3d84dcb5bfa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("b1305b2e-0d45-45c3-9576-887cf9d859e5")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("b1305b2e-0d45-45c3-9576-887cf9d859e5")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("b5821da0-308f-4f54-9a70-80eaec8a3ae3")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("b5821da0-308f-4f54-9a70-80eaec8a3ae3")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("486adbe3-853d-4198-9161-63c5398686dd")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("486adbe3-853d-4198-9161-63c5398686dd")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("6d8ff162-dba6-4f2c-a020-083d68e1cd0d")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("6d8ff162-dba6-4f2c-a020-083d68e1cd0d")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The SomeUseTag item.
            /// </summary>
            [RepositoryItem("af32cb56-1f18-4df1-b90b-32e12f2ad7a6")]
            public virtual Ranorex.UseTag SomeUseTag
            {
                get
                {
                    return _someusetagInfo.CreateAdapter<Ranorex.UseTag>(true);
                }
            }

            /// <summary>
            /// The SomeUseTag item info.
            /// </summary>
            [RepositoryItemInfo("af32cb56-1f18-4df1-b90b-32e12f2ad7a6")]
            public virtual RepoItemInfo SomeUseTagInfo
            {
                get
                {
                    return _someusetagInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwTrendyolComUyelikcbEqhttps folder.
            /// </summary>
            [RepositoryFolder("973a2329-ad2c-4b06-9687-d0f37c6580b7")]
            public virtual Scenario1RepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsFolder HttpsWwwTrendyolComUyelikcbEqhttps
            {
                get { return _httpswwwtrendyolcomuyelikcbeqhttps; }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttpsFolder folder.
        /// </summary>
        [RepositoryFolder("973a2329-ad2c-4b06-9687-d0f37c6580b7")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttpsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ueyeol1Info;
            RepoItemInfo _kadınInfo;
            RepoItemInfo _erkekInfo;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttpsFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']", parentFolder, 30000, null, false, "973a2329-ad2c-4b06-9687-d0f37c6580b7", "")
            {
                _ueyeol1Info = new RepoItemInfo(this, "UEyeOl1", "?/?/span[@innertext='Üye Ol']", "button/span[@innertext='Üye Ol']", 30000, null, "e77a2882-7098-40fc-9d09-117167fc4ffe");
                _kadınInfo = new RepoItemInfo(this, "Kadın", "div[3]/div/button[1]/span[@innertext='Kadın']", "", 30000, null, "f8c3277f-fdd0-4b56-805d-81b5632fda98");
                _erkekInfo = new RepoItemInfo(this, "Erkek", "div[3]/div/button[2]/span[@innertext='Erkek']", "", 30000, null, "41df0321-196e-49ca-9bdc-47544f38963f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("973a2329-ad2c-4b06-9687-d0f37c6580b7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("973a2329-ad2c-4b06-9687-d0f37c6580b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UEyeOl1 item.
            /// </summary>
            [RepositoryItem("e77a2882-7098-40fc-9d09-117167fc4ffe")]
            public virtual Ranorex.SpanTag UEyeOl1
            {
                get
                {
                    return _ueyeol1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl1 item info.
            /// </summary>
            [RepositoryItemInfo("e77a2882-7098-40fc-9d09-117167fc4ffe")]
            public virtual RepoItemInfo UEyeOl1Info
            {
                get
                {
                    return _ueyeol1Info;
                }
            }

            /// <summary>
            /// The Kadın item.
            /// </summary>
            [RepositoryItem("f8c3277f-fdd0-4b56-805d-81b5632fda98")]
            public virtual Ranorex.SpanTag Kadın
            {
                get
                {
                    return _kadınInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Kadın item info.
            /// </summary>
            [RepositoryItemInfo("f8c3277f-fdd0-4b56-805d-81b5632fda98")]
            public virtual RepoItemInfo KadınInfo
            {
                get
                {
                    return _kadınInfo;
                }
            }

            /// <summary>
            /// The Erkek item.
            /// </summary>
            [RepositoryItem("41df0321-196e-49ca-9bdc-47544f38963f")]
            public virtual Ranorex.SpanTag Erkek
            {
                get
                {
                    return _erkekInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Erkek item info.
            /// </summary>
            [RepositoryItemInfo("41df0321-196e-49ca-9bdc-47544f38963f")]
            public virtual RepoItemInfo ErkekInfo
            {
                get
                {
                    return _erkekInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
